rewrite PRO functions to query GraphQL
rladies/meetupr pull request #141
Opened 2022-08-20 23:14 UTC by benubah

This PR rewrites `get_pro_groups()` and `get_pro_events()` to query the new GraphQL end-points.

2022-08-29 08:29 UTC, benubah commented
@maelle Wondering how you got the old `get_pro()` functions to pass unit tests using an encrypted `meetup-pro-token` and GitHub secrets? Could you also take a look here? `R CMD check` is failing because of this. Thanks!

2022-09-28 09:25 UTC, drmowinckels requested changes
Great stuff. Just some minor changed I'd like. 
I'll get working on the token generation, its been a while, but I'm sure I can figure it out again.

2022-09-28 09:25 UTC, drmowinckels commented on R/get_pro.R
> +#' #' try(
```suggestion
#' #' \dontrun(
```

needs to be wraped in dontrun for when we submit to CRAN in the future

2022-09-28 09:25 UTC, drmowinckels commented on R/get_pro.R
>  #' #'
Would be great with a description of the `status` parameter options that can be provided, so users know what the options are.

2022-10-01 19:55 UTC, merged